### ISSUE TITLE
WPF changes...

### ISSUE THREAD

**Issue by Ephron-WL** [Aybex/ImageFilters#1]
This is a nice utility that is helpful for research.

When I cloned and opened the repo the WPF-UI 3 preview 2 was resolved by NuGet.  This no longer uses `NavigationViewBreadcrumb`, instead the name is changed to `BreadcrumbBar`.  To resolve `IconSymbol `a developer may need to specify `using Wpf.Ui.Controls.IconElements`;.

In your evaluation of upscalers, which did you feel were the best?  When I tested a half dozen using your utility, I'd say none were great, but some weren't bad.

**Comment by tomeko** [comment]
To add to this, I had to include the following in both project files of `ImageFilters.GUI` and `ImageFiltersGallery.WinUI`

`<EnableMsixTooling>true</EnableMsixTooling>`

**Comment by Aybex** [comment]
> This is a nice utility that is helpful for research.
> 
> When I cloned and opened the repo the WPF-UI 3 preview 2 was resolved by NuGet. This no longer uses `NavigationViewBreadcrumb`, instead the name is changed to `BreadcrumbBar`. To resolve `IconSymbol `a developer may need to specify `using Wpf.Ui.Controls.IconElements`;.
> 
> In your evaluation of upscalers, which did you feel were the best? When I tested a half dozen using your utility, I'd say none were great, but some weren't bad.

Hi, I haven't touched this project in a long time, but I had some spare time so I went ahead and updated it to the latest WPF-UI version as I was using a pre-release version and the API changed since.
About the resamplers, it's hard to say which is best; each one has situations where it gives better results. This is why such utility helps you understand the use cases of all common and uncommon ones.

**Comment by Aybex** [comment]
> To add to this, I had to include the following in both project files of `ImageFilters.GUI` and `ImageFiltersGallery.WinUI`
> 
> `<EnableMsixTooling>true</EnableMsixTooling>`

@tomeko  Hmm, this shouldn't be necessary, especially in the WPF Project. The WinUI project was just a test, I went ahead and removed it when updating the project.
Can you please test if the latest commit works as is?
